-- Run as ADMIN / ACCOUNTADMIN. These catalog operations need no warehouse.
-- This lab owns the JOURNEY_* objects. Use a fresh instance or clean up first.
CREATE DATABASE JOURNEY_DB;
CREATE WAREHOUSE JOURNEY_WH WAREHOUSE_SIZE = 'X-SMALL' AUTO_RESUME = TRUE AUTO_SUSPEND = 60;
CREATE ROLE JOURNEY_READER;
CREATE ROLE JOURNEY_WRITER;
GRANT ROLE JOURNEY_READER TO ROLE JOURNEY_WRITER;
CREATE USER JOURNEY_ALICE PASSWORD = 'learn-alice' DEFAULT_ROLE = JOURNEY_READER;
CREATE USER JOURNEY_BOB PASSWORD = 'learn-bob' DEFAULT_ROLE = JOURNEY_WRITER;
-- After this file, select JOURNEY_WH and JOURNEY_DB / PUBLIC in the UI.
GRANT ROLE JOURNEY_READER TO USER JOURNEY_BOB;
