-- ADMIN, ACCOUNTADMIN, JOURNEY_WH, JOURNEY_DB, PUBLIC.
CREATE TABLE source_users (id INTEGER, name VARCHAR, region VARCHAR);
CREATE TABLE processed_users (id INTEGER, name VARCHAR, region VARCHAR);
CREATE TRANSIENT TABLE procedure_log (message VARCHAR);
CREATE TEMPORARY TABLE scratch_users AS SELECT 42 AS answer;
SELECT answer FROM scratch_users;

CREATE STAGE users_stage;
CREATE STREAM users_stream ON TABLE source_users APPEND_ONLY = TRUE;
CREATE VIEW users_view AS SELECT id, name, region FROM source_users;

GRANT USAGE ON WAREHOUSE JOURNEY_WH TO ROLE JOURNEY_READER;
GRANT USAGE ON DATABASE JOURNEY_DB TO ROLE JOURNEY_READER;
GRANT USAGE ON SCHEMA JOURNEY_DB.PUBLIC TO ROLE JOURNEY_READER;
GRANT SELECT ON TABLE JOURNEY_DB.PUBLIC.SOURCE_USERS TO ROLE JOURNEY_READER;
GRANT INSERT ON TABLE JOURNEY_DB.PUBLIC.SOURCE_USERS TO ROLE JOURNEY_WRITER;
GRANT UPDATE ON TABLE JOURNEY_DB.PUBLIC.SOURCE_USERS TO ROLE JOURNEY_WRITER;
-- After this file, refresh Objects and upload users.csv to USERS_STAGE.
GRANT DELETE ON TABLE JOURNEY_DB.PUBLIC.SOURCE_USERS TO ROLE JOURNEY_WRITER;
