-- ADMIN / ACCOUNTADMIN, JOURNEY_WH, JOURNEY_DB / PUBLIC.
-- Deletes only this lab's objects, data, accounts, grants, and uploaded file.
DROP TASK IF EXISTS process_users_task;
DROP DYNAMIC TABLE IF EXISTS users_by_region;
DROP PROCEDURE IF EXISTS process_users();
DROP STREAM IF EXISTS users_stream;
DROP VIEW IF EXISTS users_view;
DROP STAGE IF EXISTS users_stage;
DROP TABLE IF EXISTS scratch_users;
DROP TABLE IF EXISTS procedure_log;
DROP TABLE IF EXISTS processed_users;
DROP TABLE IF EXISTS source_users;
DROP USER IF EXISTS JOURNEY_BOB;
DROP USER IF EXISTS JOURNEY_ALICE;
REVOKE ROLE JOURNEY_READER FROM ROLE JOURNEY_WRITER;
DROP ROLE IF EXISTS JOURNEY_WRITER;
DROP ROLE IF EXISTS JOURNEY_READER;
