SHOW USERS;
SHOW ROLES;

CREATE DATABASE PHASE7_DB;

CREATE WAREHOUSE PHASE7_WH
  WAREHOUSE_SIZE = X-SMALL
  AUTO_RESUME = TRUE
  AUTO_SUSPEND = 60;

CREATE ROLE PHASE7_READER COMMENT = 'Can read the phase 7 table';
CREATE ROLE PHASE7_WRITER COMMENT = 'Can modify the phase 7 table';

CREATE TABLE PHASE7_DB.PUBLIC.LESSON_USERS (
  ID INTEGER,
  NAME VARCHAR
);

SELECT CURRENT_USER() AS current_user, CURRENT_ROLE() AS current_role;

INSERT INTO PHASE7_DB.PUBLIC.LESSON_USERS VALUES
  (1, 'Ada'),
  (2, 'Grace');

GRANT USAGE ON WAREHOUSE PHASE7_WH TO ROLE PHASE7_READER;
GRANT USAGE ON DATABASE PHASE7_DB TO ROLE PHASE7_READER;
GRANT USAGE ON SCHEMA PHASE7_DB.PUBLIC TO ROLE PHASE7_READER;
GRANT SELECT ON TABLE PHASE7_DB.PUBLIC.LESSON_USERS TO ROLE PHASE7_READER;

GRANT INSERT ON TABLE PHASE7_DB.PUBLIC.LESSON_USERS TO ROLE PHASE7_WRITER;
GRANT UPDATE ON TABLE PHASE7_DB.PUBLIC.LESSON_USERS TO ROLE PHASE7_WRITER;
GRANT DELETE ON TABLE PHASE7_DB.PUBLIC.LESSON_USERS TO ROLE PHASE7_WRITER;

GRANT ROLE PHASE7_READER TO ROLE PHASE7_WRITER;

CREATE USER PHASE7_STUDENT
  PASSWORD = 'learn-phase-7'
  DEFAULT_ROLE = PHASE7_WRITER
  DISABLED = FALSE
  COMMENT = 'Frontend authentication demonstration user';

GRANT ROLE PHASE7_READER TO USER PHASE7_STUDENT;
GRANT ROLE PHASE7_WRITER TO USER PHASE7_STUDENT;

SHOW GRANTS TO USER PHASE7_STUDENT;
SHOW GRANTS TO ROLE PHASE7_READER;
SHOW GRANTS TO ROLE PHASE7_WRITER;

SELECT
  CURRENT_USER() AS current_user,
  CURRENT_ROLE() AS current_role;

SELECT *
FROM PHASE7_DB.PUBLIC.LESSON_USERS
ORDER BY ID;

INSERT INTO PHASE7_DB.PUBLIC.LESSON_USERS VALUES (3, 'Linus');

UPDATE PHASE7_DB.PUBLIC.LESSON_USERS
SET NAME = 'Linus Torvalds'
WHERE ID = 3;

SELECT *
FROM PHASE7_DB.PUBLIC.LESSON_USERS
ORDER BY ID;

SELECT
  CURRENT_USER() AS current_user,
  CURRENT_ROLE() AS current_role;

SELECT *
FROM PHASE7_DB.PUBLIC.LESSON_USERS
ORDER BY ID;

INSERT INTO PHASE7_DB.PUBLIC.LESSON_USERS VALUES (4, 'Should fail');

SELECT CURRENT_ROLE() AS current_role;

DELETE FROM PHASE7_DB.PUBLIC.LESSON_USERS WHERE ID = 3;

SELECT *
FROM PHASE7_DB.PUBLIC.LESSON_USERS
ORDER BY ID;

SHOW USERS;
SHOW ROLES;
SHOW GRANTS TO USER PHASE7_STUDENT;

DROP USER IF EXISTS PHASE7_STUDENT;
DROP ROLE IF EXISTS PHASE7_WRITER;
DROP ROLE IF EXISTS PHASE7_READER;
DROP WAREHOUSE PHASE7_WH;
DROP DATABASE PHASE7_DB;

SHOW USERS;
SHOW ROLES;
