-- Identity SQL management worksheet (phase 3).
-- Run statements individually. Identity DDL and SHOW commands do not require
-- a warehouse because they only modify or read the emulator catalog.

SHOW USERS;
SHOW ROLES;

CREATE ROLE IF NOT EXISTS STUDY_DEVELOPER COMMENT = 'Local study role';
CREATE ROLE IF NOT EXISTS STUDY_READER COMMENT = 'Read-oriented child role';

CREATE WAREHOUSE STUDY_WH WAREHOUSE_SIZE = X-SMALL AUTO_RESUME = TRUE AUTO_SUSPEND = 60;
GRANT USAGE ON WAREHOUSE STUDY_WH TO ROLE STUDY_READER;
GRANT OPERATE ON WAREHOUSE STUDY_WH TO ROLE STUDY_DEVELOPER;
GRANT USAGE ON DATABASE LEARNING_DB TO ROLE STUDY_READER;
GRANT USAGE ON SCHEMA LEARNING_DB.PUBLIC TO ROLE STUDY_READER;
GRANT CREATE TABLE ON SCHEMA LEARNING_DB.PUBLIC TO ROLE STUDY_DEVELOPER;
GRANT SELECT ON TABLE LEARNING_DB.PUBLIC.USERS TO ROLE STUDY_READER;
GRANT INSERT ON TABLE LEARNING_DB.PUBLIC.USERS TO ROLE STUDY_DEVELOPER;

CREATE USER STUDENT_ONE
  PASSWORD = 'learn-locally'
  DEFAULT_ROLE = STUDY_DEVELOPER
  DISABLED = FALSE
  COMMENT = 'Worksheet demonstration user';

GRANT ROLE STUDY_READER TO ROLE STUDY_DEVELOPER;
GRANT ROLE STUDY_READER TO USER STUDENT_ONE;

SHOW GRANTS TO USER STUDENT_ONE;
SHOW GRANTS TO ROLE STUDY_DEVELOPER;
SHOW GRANTS OF ROLE STUDY_READER;

-- Connect as STUDENT_ONE with STUDY_DEVELOPER active to exercise caller-rights.
-- The inherited STUDY_READER grant supplies warehouse USAGE.
CREATE PROCEDURE CURRENT_STUDY_ROLE()
  RETURNS VARCHAR
  LANGUAGE SQL
  AS $$ BEGIN RETURN CURRENT_ROLE(); END $$;
CALL CURRENT_STUDY_ROLE();

CREATE TABLE STREAM_SOURCE (ID INTEGER);
CREATE STREAM STUDY_STREAM ON TABLE STREAM_SOURCE;
INSERT INTO STREAM_SOURCE VALUES (1);
SELECT * FROM STUDY_STREAM;

ALTER USER STUDENT_ONE SET PASSWORD = 'new-local-password';
ALTER USER STUDENT_ONE SET COMMENT = 'Password changed during worksheet';
ALTER USER STUDENT_ONE SET DISABLED = TRUE;
SHOW USERS;
ALTER USER STUDENT_ONE SET DISABLED = FALSE;

REVOKE ROLE STUDY_READER FROM USER STUDENT_ONE;
REVOKE ROLE STUDY_READER FROM ROLE STUDY_DEVELOPER;
REVOKE USAGE ON WAREHOUSE STUDY_WH FROM ROLE STUDY_READER;
REVOKE OPERATE ON WAREHOUSE STUDY_WH FROM ROLE STUDY_DEVELOPER;

DROP USER IF EXISTS STUDENT_ONE;
DROP ROLE IF EXISTS STUDY_READER;
DROP ROLE IF EXISTS STUDY_DEVELOPER;
DROP WAREHOUSE STUDY_WH;

SHOW USERS;
SHOW ROLES;
