-- Identity SQL management worksheet (phase 3).
-- Run statements individually. Identity DDL and SHOW commands do not require
-- a warehouse because they only modify or read the emulator catalog.

SHOW USERS;
SHOW ROLES;

CREATE ROLE IF NOT EXISTS STUDY_DEVELOPER COMMENT = 'Local study role';
CREATE ROLE IF NOT EXISTS STUDY_READER COMMENT = 'Read-oriented child role';

CREATE WAREHOUSE STUDY_WH WAREHOUSE_SIZE = X-SMALL AUTO_RESUME = TRUE AUTO_SUSPEND = 60;
GRANT USAGE ON WAREHOUSE STUDY_WH TO ROLE STUDY_READER;
GRANT OPERATE ON WAREHOUSE STUDY_WH TO ROLE STUDY_DEVELOPER;

CREATE USER STUDENT_ONE
  PASSWORD = 'learn-locally'
  DEFAULT_ROLE = STUDY_DEVELOPER
  DISABLED = FALSE
  COMMENT = 'Worksheet demonstration user';

GRANT ROLE STUDY_READER TO ROLE STUDY_DEVELOPER;
GRANT ROLE STUDY_READER TO USER STUDENT_ONE;

SHOW GRANTS TO USER STUDENT_ONE;
SHOW GRANTS TO ROLE STUDY_DEVELOPER;
SHOW GRANTS OF ROLE STUDY_READER;

ALTER USER STUDENT_ONE SET PASSWORD = 'new-local-password';
ALTER USER STUDENT_ONE SET COMMENT = 'Password changed during worksheet';
ALTER USER STUDENT_ONE SET DISABLED = TRUE;
SHOW USERS;
ALTER USER STUDENT_ONE SET DISABLED = FALSE;

REVOKE ROLE STUDY_READER FROM USER STUDENT_ONE;
REVOKE ROLE STUDY_READER FROM ROLE STUDY_DEVELOPER;
REVOKE USAGE ON WAREHOUSE STUDY_WH FROM ROLE STUDY_READER;
REVOKE OPERATE ON WAREHOUSE STUDY_WH FROM ROLE STUDY_DEVELOPER;

DROP USER IF EXISTS STUDENT_ONE;
DROP ROLE IF EXISTS STUDY_READER;
DROP ROLE IF EXISTS STUDY_DEVELOPER;
DROP WAREHOUSE STUDY_WH;

SHOW USERS;
SHOW ROLES;
